project:
  type: manuscript

execute:
  freeze: auto

format: 
  html:
    toc: true
    comments:
      hypothesis: true
    css: styles.css
  pdf:
    toc: false
    number-sections: true
  docx:
    toc: false
    number-sections: true
theme: default
